name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        platforms: 
          - linux/arm/v7
          - linux/arm64
    steps:
    - 
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: ${{ matrix.platform }}
    - 
      name: Build Setup
      run: |
        /bin/bash build_workflow.sh ${{ matrix.platform }}
