name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy: 
      matrix:
        platforms: 
          - armhf
          - aarch64
    steps:
    - 
      uses: actions/checkout@v2
    -
      name: Install dependencies
      run: |
        echo "deb https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu focal main" | sudo tee -a /etc/apt/sources.list
        echo "deb-src https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu focal main" | sudo tee -a /etc/apt/sources.list
        sudo apt update || true
        sudo apt install qemu binfmt-support qemu-user-static crossbuild-essential-arm64 crossbuild-essential-armhf
        sudo apt-get install git autoconf libtool automake build-essential gettext cmake python3 curl squashfs-tools mono-complete
    - 
      name: Build Setup
      run: |
        /bin/bash build_workflow.sh ${{ matrix.platforms }}
    - 
      name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mono-${GITHUB_SHA::8}-${{ matrix.platforms }}
        path: built/mono-${GITHUB_SHA::8}-${{ matrix.platforms }}.squashfs
