name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy: 
      matrix:
        platforms: 
          - linux/arm/v7
          - linux/arm64
    steps:
    - 
      uses: actions/checkout@v2
    -
      name: Install dependencies
      run: |
        echo "deb https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list
        echo "deb-src https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu bionic main" | sudo tee -a /etc/apt/sources.list
        sudo dpkg --add-architecture armhf
        sudo dpkg --add-architecture arm64
        sudo apt update || true
        sudo apt install qemu binfmt-support qemu-user-static libc6:armhf libc6:arm64
        sudo apt-get install git autoconf libtool automake build-essential gettext cmake python3 curl squashfs-tools mono-complete crossbuild-essential-arm64 crossbuild-essential-armhf
    - 
      name: Build Setup
      run: |
        /bin/bash build_workflow.sh ${{ matrix.platforms }}
